import PptxGenJS from 'pptxgenjs';
import type { ResearchData } from './types';

export function generatePPT(data: ResearchData, topic: string): PptxGenJS {
  const pptx = new PptxGenJS();

  // 슬라이드 추가
  const slide = pptx.addSlide();

  // 배경색 설정
  slide.background = { color: 'FFFFFF' };

  // 타이틀
  slide.addText(topic, {
    x: 0.5,
    y: 0.5,
    w: 9,
    h: 0.8,
    fontSize: 28,
    bold: true,
    color: '1F4788',
    align: 'left',
  });

  // 생성 정보
  const today = new Date().toLocaleDateString('ko-KR');
  slide.addText(`Generated by KKAM_BIZ | ${today}`, {
    x: 0.5,
    y: 1.2,
    w: 9,
    h: 0.4,
    fontSize: 12,
    color: '666666',
    align: 'left',
  });

  // 구분선
  slide.addShape(pptx.ShapeType.rect, {
    x: 0.5,
    y: 1.8,
    w: 9,
    h: 0.02,
    fill: { color: 'CCCCCC' },
  });

  // 핵심 트렌드 섹션
  slide.addText('📊 핵심 트렌드', {
    x: 0.5,
    y: 2.1,
    w: 9,
    h: 0.5,
    fontSize: 20,
    bold: true,
    color: '1F4788',
  });

  // 트렌드 목록
  let yPosition = 2.7;
  data.trends.slice(0, 3).forEach((trend, index) => {
    // 트렌드 제목
    slide.addText(`${index + 1}. ${trend.title}`, {
      x: 0.7,
      y: yPosition,
      w: 8.5,
      h: 0.4,
      fontSize: 16,
      bold: true,
      color: '333333',
    });

    // 트렌드 설명
    slide.addText(`- ${trend.description}`, {
      x: 0.9,
      y: yPosition + 0.4,
      w: 8.3,
      h: 0.5,
      fontSize: 12,
      color: '666666',
    });

    yPosition += 1.1;
  });

  // 시사점 섹션
  slide.addText('💡 So What? (시사점)', {
    x: 0.5,
    y: yPosition + 0.2,
    w: 9,
    h: 0.5,
    fontSize: 20,
    bold: true,
    color: '1F4788',
  });

  // 시사점 목록
  let insightY = yPosition + 0.8;
  data.insights.slice(0, 2).forEach((insight) => {
    slide.addText(`- ${insight}`, {
      x: 0.7,
      y: insightY,
      w: 8.5,
      h: 0.4,
      fontSize: 12,
      color: '333333',
    });
    insightY += 0.45;
  });

  // 출처
  const sources = data.sources.slice(0, 3).map((s) => s.title || s.url).join(', ');
  slide.addText(`📎 출처: ${sources}`, {
    x: 0.5,
    y: 7,
    w: 9,
    h: 0.4,
    fontSize: 10,
    color: '999999',
  });

  return pptx;
}
